language: node_js
cache:
  yarn: true
  apt: true
sudo: required
dist: bionic
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
- sudo apt-get -y install pkg-config
- sudo bash packages/flamingo/tools/install-ffmpeg.sh
- sudo bash packages/flamingo/tools/install-imagemagick.sh
- sudo bash packages/flamingo/tools/install-graphicsmagick.sh
- ls -la packages/flamingo/test/fixtures/images

stages:
- test
- benchmark

jobs:
  include:
  - stage: test
    node_js: 'node'
    script: yarn test
  - stage: test
    node_js: 'lts/erbium'
    script: yarn test
  - stage: benchmark
    node_js: 'lts/erbium'
    script: yarn bench
