// flow-typed signature: 61182e31a23013950a0ebc2bf00e32f6
// flow-typed version: <<STUB>>/buffer-peek-stream_v^1.0.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'buffer-peek-stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'buffer-peek-stream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'buffer-peek-stream/buffer-peek-stream' {
  declare module.exports: any;
}

declare module 'buffer-peek-stream/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'buffer-peek-stream/buffer-peek-stream.js' {
  declare module.exports: $Exports<'buffer-peek-stream/buffer-peek-stream'>;
}
declare module 'buffer-peek-stream/test.js' {
  declare module.exports: $Exports<'buffer-peek-stream/test'>;
}
