// flow-typed signature: 11c647a7e3e7ddbe436813cfdddf316a
// flow-typed version: <<STUB>>/mimeparse_v^0.1.4/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mimeparse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mimeparse' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mimeparse/lib/mimeparse' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mimeparse/lib/mimeparse.js' {
  declare module.exports: $Exports<'mimeparse/lib/mimeparse'>;
}
