// flow-typed signature: ae267909d6566423cb7a2cf746dcee2e
// flow-typed version: <<STUB>>/optional_v^0.1.3/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'optional'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'optional' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'optional/optional' {
  declare module.exports: any;
}

declare module 'optional/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'optional/optional.js' {
  declare module.exports: $Exports<'optional/optional'>;
}
declare module 'optional/test.js' {
  declare module.exports: $Exports<'optional/test'>;
}
