// flow-typed signature: 84f18057bf61bd6b01930f466e556e3e
// flow-typed version: <<STUB>>/postman-jsdoc-theme_v0.0.2/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postman-jsdoc-theme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postman-jsdoc-theme' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postman-jsdoc-theme/publish' {
  declare module.exports: any;
}

declare module 'postman-jsdoc-theme/static/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'postman-jsdoc-theme/static/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'postman-jsdoc-theme/static/scripts/prettify/prettify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postman-jsdoc-theme/publish.js' {
  declare module.exports: $Exports<'postman-jsdoc-theme/publish'>;
}
declare module 'postman-jsdoc-theme/static/scripts/linenumber.js' {
  declare module.exports: $Exports<'postman-jsdoc-theme/static/scripts/linenumber'>;
}
declare module 'postman-jsdoc-theme/static/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'postman-jsdoc-theme/static/scripts/prettify/lang-css'>;
}
declare module 'postman-jsdoc-theme/static/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'postman-jsdoc-theme/static/scripts/prettify/prettify'>;
}
