// flow-typed signature: f4d5812c8fcab1a7279cf5f200f134c0
// flow-typed version: <<STUB>>/sharp_v^0.16.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sharp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'sharp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sharp/binding' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sharp/binding.js' {
  declare module.exports: $Exports<'sharp/binding'>;
}
declare module 'sharp/index' {
  declare module.exports: $Exports<'sharp'>;
}
declare module 'sharp/index.js' {
  declare module.exports: $Exports<'sharp'>;
}
