name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node: [ '14', '15' ]

    name: Node ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 4
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install native dependencies
        run: |
          sudo apt-get -y install pkg-config ffmpeg
          sudo bash packages/flamingo/tools/install-graphicsmagick.sh
      - run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test-changed

  bench:
    needs: [ build ]
    runs-on: ubuntu-18.04
    name: Benchmark

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15
      - name: Install native dependencies
        run: |
          sudo apt-get -y install pkg-config ffmpeg
          sudo bash packages/flamingo/tools/install-imagemagick.sh
          sudo bash packages/flamingo/tools/install-graphicsmagick.sh
      - run: yarn install --frozen-lockfile
      - run: yarn bench
